### ISSUE TITLE
这是开发完了吗？

### ISSUE THREAD

**Issue by bubao** [Dreagonmon/TpnsApi#1]
rt

**Comment by Dreagonmon** [comment]
一年多前，这是开发完了的，现在要测试一下兼容性才知道能不能正常工作。这里只是简单的包装了一下nodejs内置模块，自动完成请求的签名，具体API接口要看TPNS文档。

**Comment by Dreagonmon** [comment]
看了下TPNS文档，签名方式没变，请求接口没变，应该能正常工作。

**Comment by bubao** [comment]
我没看懂它这个前端APP和后端是怎么样的调用的
